config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tasks

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  enum priority: { low: 0, mid: 1, high: 2 }
  enum status: { not_yet: 0, in_progress: 1, done: 2 }

  has_and_belongs_to_many :labels
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :deadline_on, presence: true
  validates :priority, presence: true
  validates :status, presence: true

  scope :newer, -> { order(created_at: :desc) }

  def self.searched_by(subjects, user)
    result = Task.where(user: user)

    return result unless subjects

    result = result.where(status: subjects[:status]) if subjects[:status].present?
    result = result.where('tasks.title LIKE ?', "%#{subjects[:title]}%") if subjects[:title].present?
    result = result.joins(:labels).where('labels.id': subjects[:label_id]) if subjects[:label_id].present?
    result
  end

  def self.desc_sort_by(column, direction)
    return newer unless column
    return newer unless %w[due_on priority].include?(column)
    return newer unless %w[ASC DESC].include?(direction)

    order("#{column} #{direction}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  after_update :prevent_changing_admin
  after_destroy :prevent_removing_admin

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  private

  def prevent_changing_admin
    return if self.class.where(admin: true).exists?
    errors.add(:base, I18n.t('errors.messages.prevent_changing_admin'))

    raise ActiveRecord::Rollback, self
  end

  def prevent_removing_admin
    return if self.class.where(admin: true).exists?
    raise ActiveRecord::Rollback
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_required
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.includes(:tasks).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: t('.created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: t('.destroyed')
    else
      redirect_to admin_users_path, notice: t('.prevent_removing_admin')
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_user

  def admin_required
    redirect_to tasks_path, notice: t('common.admin_required') unless current_user.admin?
  end

  private

  def require_login
    unless current_user
      flash[:notice] = t('common.require_login')
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[edit update destroy]

  def index
    @labels = current_user.labels
  end

  def new
    @label = current_user.labels.new
  end

  def create
    @label = current_user.labels.build(label_params)

    if @label.save
      redirect_to labels_path, notice: t('.created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path, notice: t('.destroyed')
  end

  private

    def set_label
      begin
        @label = current_user.labels.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to labels_path
      end
    end

    def label_params
      params.require(:label).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    redirect_to tasks_path, notice: t('common.require_logout') if current_user
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: t('.logged_in')
    else
      flash.now[:notice] = t('.email_or_password_wrong')
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path, notice: t('.logged_out')
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = current_user.tasks.searched_by(params[:search], current_user).desc_sort_by(params[:sort_column], params[:direction]).newer.page(params[:page])
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: t('.created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('.destroyed')
  end

  private
    def set_task
      begin
        @task = current_user.tasks.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to tasks_path, notice: t('common.require_correct_user')
      end
    end

    def task_params
      params.require(:task).permit(:title, :content, :deadline_on, :priority, :status, label_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: %i[show edit update destroy]

  def new
    redirect_to tasks_path, notice: t('common.require_logout') if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path, notice: t('.created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('.updated')
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @user, url: admin_user_path, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="field">
    <%= f.submit nil, id: "update-user" %>
  </div>
<% end %>

<br>

<%= link_to t('common.back'), admin_users_path, id: 'back' %>

app/views/admin/users/index.html.erb
<h1><%= t('.title') %></h1>
<%= paginate @users %>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= User.human_attribute_name(:admin) %></th>
      <th><%= t('.registered_tasks_count') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.admin? %>
            <%= t(".admin_true") %>
          <% else %>
            <%= t(".admin_false") %>
          <% end %>
        </td>
        <td><%= user.tasks.pluck(:title).size %></td>
        <td><%= link_to t('common.show'), admin_user_path(user), class: 'show-user' %></td>
        <td><%= link_to t('common.edit'), edit_admin_user_path(user), class: 'edit-user' %></td>
        <td><%= link_to t('common.destroy'), admin_user_path(user), method: :delete, data: { confirm: t('common.confirm_destroy') }, class: 'destroy-user' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @user, url: admin_users_path, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="field">
    <%= f.submit nil, id: "create-user" %>
  </div>
<% end %>

<br>

<%= link_to t('common.back'), admin_users_path, id: 'back' %>

app/views/admin/users/show.html.erb
<h1><%= t('.title') %></h1>

<p>
  <strong><%= User.human_attribute_name(:name) %>:</strong>
  <%= @user.name %>
</p>

<p>
  <strong><%= User.human_attribute_name(:email) %>:</strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= User.human_attribute_name(:admin) %>:</strong>
  <% if @user.admin? %>
    <%= t(".admin_true") %>
  <% else %>
    <%= t(".admin_false") %>
  <% end %>
</p>

<table>
  <thead>
    <tr>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <th><%= Task.human_attribute_name(:deadline_on) %></th>
      <th><%= Task.human_attribute_name(:priority) %></th>
      <th><%= Task.human_attribute_name(:status) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= task.deadline_on %></td>
        <td><%= t("enum.task.priority.#{task.priority}") %></td>
        <td><%= t("enum.task.status.#{task.status}") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('common.back'), tasks_path, id: 'back' %>

app/views/labels/edit.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @label, local: true do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit nil, id: 'update-label' %>
  </div>
<% end %>

<%= link_to t('common.back'), labels_path, id: 'back' %>

app/views/labels/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Label.human_attribute_name(:name) %></th>
      <th><%= t('.registered_tasks_count') %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.tasks.size %></td>
        <td><%= link_to t('common.edit'), edit_label_path(label), class: 'edit-label' %></td>
        <td><%= link_to t('common.destroy'), label, method: :delete, data: { confirm: t('common.confirm_destroy') }, class: 'destroy-label' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/labels/new.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @label, local: true do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit nil, id: 'create-label' %>
  </div>
<% end %>

<%= link_to t('common.back'), labels_path, id: 'back' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CdpWebManyoTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if current_user&.admin? %>
        <li><%= link_to t('global_navigation.users_index'), admin_users_path, id: "users-index" %></li>
        <li><%= link_to t('global_navigation.new_user'), new_admin_user_path, id: "new-user" %></li>
      <% end %>

      <% if current_user %>
        <li><%= link_to t('global_navigation.tasks_index'), tasks_path, id: 'tasks-index' %></li>
        <li><%= link_to t('global_navigation.new_task'), new_task_path, id: 'new-task' %></li>
        <li><%= link_to t('global_navigation.labels_index'), labels_path, id: 'labels-index' %></li>
        <li><%= link_to t('global_navigation.new_label'), new_label_path, id: 'new-label' %></li>
        <li><%= link_to t('global_navigation.my_account'), current_user, id: "my-account" %></li>
        <li><%= link_to t('global_navigation.logout'), session_path(current_user), method: :delete, id: "sign-out" %></li>
      <% else %>
        <li><%= link_to t('global_navigation.sign_up'), new_user_path, id: "sign-up" %></li>
        <li><%= link_to t('global_navigation.login'), new_session_path, id: "sign-in" %></li>
      <% end %>
    </ul>

    <% if flash.notice.present? %>
      <%= flash.notice %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @task, local: true do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :deadline_on %>
    <%= f.date_field :deadline_on %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities.map { |k, v| [t("enum.task.priority.#{k}"), k] } %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.map { |k, v| [t("enum.task.status.#{k}"), k] } %>
  </div>

  <div class="field">
    <%= f.label t("activerecord.models.label") %>
    <div class="checkbox-field">
      <%= f.collection_check_boxes :label_ids, current_user.labels, :id, :name %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit nil, id: 'update-task' %>
  </div>
<% end %>

<%= link_to t('common.back'), tasks_path, id: 'back' %>

app/views/tasks/index.html.erb
<h1><%= t('.title') %></h1>

<%= form_with url: tasks_path, scope: :search, method: :get, local: true do |f| %>
  <div class="field">
    <%= f.label Task.human_attribute_name(:status) %>
    <%= f.select :status, Task.statuses.map { |k, v| [t("enum.task.status.#{k}"), k] }, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label Task.human_attribute_name(:title) %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label Task.human_attribute_name(:label) %>
    <%= f.select :label_id, current_user.labels.map { |l| [l.name, l.id] }, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit_search'), id: 'search_task' %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <th><%= link_to Task.human_attribute_name(:deadline_on), sort_column: :deadline_on, direction: 'ASC', id: "test" %></th>
      <th><%= link_to Task.human_attribute_name(:priority), sort_column: :priority, direction: 'DESC' %></th>
      <th><%= Task.human_attribute_name(:status) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= task.deadline_on %></td>
        <td><%= t("enum.task.priority.#{task.priority}") %></td>
        <td><%= t("enum.task.status.#{task.status}") %></td>
        <td><%= link_to t('common.show'), task, class: 'show-task' %></td>
        <td><%= link_to t('common.edit'), edit_task_path(task), class: 'edit-task' %></td>
        <td><%= link_to t('common.destroy'), task, method: :delete, data: { confirm: t('common.confirm_destroy') }, class: 'destroy-task' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @task, local: true do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :deadline_on %>
    <%= f.date_field :deadline_on %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities.map { |k, v| [t("enum.task.priority.#{k}"), k] }, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.map { |k, v| [t("enum.task.status.#{k}"), k] }, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label t("activerecord.models.label") %>
    <div class="checkbox-field">
      <%= f.collection_check_boxes :label_ids, current_user.labels, :id, :name %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit nil, id: 'create-task' %>
  </div>
<% end %>

<%= link_to t('common.back'), tasks_path, id: 'back' %>

app/views/tasks/show.html.erb
<h1><%= t('.title') %></h1>

<p>
  <strong><%= Task.human_attribute_name(:title) %>:</strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= Task.human_attribute_name(:content) %>:</strong>
  <%= @task.content %>
</p>

<p>
  <strong><%= Task.human_attribute_name(:created_at) %>:</strong>
  <%= @task.created_at.strftime('%Y/%m/%d %H:%M') %>
</p>

<p>
  <strong><%= Task.human_attribute_name(:deadline_on) %>:</strong>
  <span><%= @task.deadline_on %></span>
</p>

<p>
  <strong><%= Task.human_attribute_name(:priority) %>:</strong>
  <span><%= t("enum.task.priority.#{@task.priority}") %></span>
</p>

<p>
  <strong><%= Task.human_attribute_name(:status) %>:</strong>
  <span><%= t("enum.task.status.#{@task.status}") %></span>
</p>

<p>
  <strong><%= t("activerecord.models.label") %>:</strong>
  <% @task.labels.each do |label| %>
    <span><%= label.name %></span>
  <% end %>
</p>

<%= link_to t('common.edit'), edit_task_path, id: 'edit-task' %> |
<%= link_to t('common.back'), tasks_path, id: 'back' %>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit nil, id: "update-user" %>
  </div>
<% end %>

<br>

<%= link_to t('common.back'), @user, id: 'back' %>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit nil, id: "create-user" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= t('.title') %></h1>

<p>
  <strong><%= User.human_attribute_name(:name) %>:</strong>
  <span><%= @user.name %></span>
</p>

<p>
  <strong><%= User.human_attribute_name(:email) %>:</strong>
  <span><%= @user.email %></span>
</p>

<br>

<%= link_to t('common.edit'), edit_user_path, id: 'edit-user' %> |
<%= link_to t('common.back'), tasks_path, id: 'back' %>